#!/bin/bash
# ============================================================
# tmux-theme.sh — Sync tmux colors to the active Neovim theme
# Called by Neovim's theme_selector.lua after saving a theme.
# ============================================================

THEME="${1:-}"

# If no argument, try to read from the nvim theme config file
if [ -z "$THEME" ]; then
    THEME_FILE="$HOME/.config/nvim/lua/plugins/theme.lua"
    if [ -f "$THEME_FILE" ]; then
        THEME=$(grep -oE '"[^"]+"' "$THEME_FILE" | tr -d '"' | head -n1)
    fi
fi

THEME="${THEME:-tokyonight}"

# Normalize variant names to base theme names for palette lookup
case "$THEME" in
    tokyonight*)          BASE="tokyonight" ;;
    catppuccin-latte)     BASE="catppuccin-latte" ;;
    catppuccin*)          BASE="catppuccin" ;;
    rose-pine-dawn)       BASE="rose-pine-dawn" ;;
    rose-pine*)           BASE="rose-pine" ;;
    kanagawa-wave)        BASE="kanagawa" ;;
    kanagawa*)            BASE="kanagawa" ;;
    nightfox|nordfox*)    BASE="nightfox" ;;
    gruvbox*)             BASE="gruvbox" ;;
    nord*)                BASE="nord" ;;
    vscode*)              BASE="vscode" ;;
    matteblack*)          BASE="matteblack" ;;
    cyberdream*)          BASE="cyberdream" ;;
    aether*)              BASE="aether" ;;
    *)                    BASE="tokyonight" ;;
esac

# ── Palette definitions ────────────────────────────────────────
# Each theme defines: BG FG ACCENT ACCENT2 MUTED BORDER
case "$BASE" in
    tokyonight)
        BG="#1a1b26"       FG="#c0caf5"
        ACCENT="#7aa2f7"   ACCENT2="#9ece6a"
        MUTED="#565f89"    BORDER="#3b4261"
        ;;
    catppuccin)
        BG="#1e1e2e"       FG="#cdd6f4"
        ACCENT="#89b4fa"   ACCENT2="#a6e3a1"
        MUTED="#6c7086"    BORDER="#313244"
        ;;
    catppuccin-latte)
        BG="#eff1f5"       FG="#4c4f69"
        ACCENT="#1e66f5"   ACCENT2="#40a02b"
        MUTED="#9ca0b0"    BORDER="#ccd0da"
        ;;
    gruvbox)
        BG="#282828"       FG="#ebdbb2"
        ACCENT="#d79921"   ACCENT2="#98971a"
        MUTED="#928374"    BORDER="#504945"
        ;;
    nord)
        BG="#2e3440"       FG="#d8dee9"
        ACCENT="#88c0d0"   ACCENT2="#a3be8c"
        MUTED="#4c566a"    BORDER="#3b4252"
        ;;
    vscode)
        BG="#1e1e1e"       FG="#d4d4d4"
        ACCENT="#569cd6"   ACCENT2="#4ec9b0"
        MUTED="#6a9955"    BORDER="#3c3c3c"
        ;;
    matteblack)
        BG="#0d0d0d"       FG="#c8c8c8"
        ACCENT="#5c9ad6"   ACCENT2="#6a9955"
        MUTED="#444444"    BORDER="#2a2a2a"
        ;;
    rose-pine)
        BG="#191724"       FG="#e0def4"
        ACCENT="#c4a7e7"   ACCENT2="#9ccfd8"
        MUTED="#6e6a86"    BORDER="#26233a"
        ;;
    rose-pine-dawn)
        BG="#faf4ed"       FG="#575279"
        ACCENT="#907aa9"   ACCENT2="#56949f"
        MUTED="#9893a5"    BORDER="#f2e9e1"
        ;;
    kanagawa)
        BG="#1f1f28"       FG="#dcd7ba"
        ACCENT="#7e9cd8"   ACCENT2="#98bb6c"
        MUTED="#727169"    BORDER="#2a2a37"
        ;;
    nightfox)
        BG="#192330"       FG="#cdcecf"
        ACCENT="#81a1c1"   ACCENT2="#a3be8c"
        MUTED="#39506d"    BORDER="#212e3f"
        ;;
    cyberdream)
        BG="#16181a"       FG="#ffffff"
        ACCENT="#5ea1ff"   ACCENT2="#5eff6c"
        MUTED="#3c4048"    BORDER="#272b2e"
        ;;
    aether)
        BG="#0f0f17"       FG="#c8ccd4"
        ACCENT="#7b8dd8"   ACCENT2="#78b89a"
        MUTED="#4a4f63"    BORDER="#1e2030"
        ;;
    *)
        BG="#1a1b26"       FG="#c0caf5"
        ACCENT="#7aa2f7"   ACCENT2="#9ece6a"
        MUTED="#565f89"    BORDER="#3b4261"
        ;;
esac

# ── Write tmux color config ────────────────────────────────────
COLORS_FILE="${HOME}/.config/tmux/tmux-colors.conf"
mkdir -p "$(dirname "$COLORS_FILE")"

cat > "$COLORS_FILE" << EOF
# Auto-generated by tmux-theme.sh — theme: ${THEME}
# DO NOT EDIT MANUALLY

set -g status-style "bg=${BG},fg=${MUTED}"
set -g status-left "#[fg=${BG},bg=${ACCENT},bold] #S #[bg=${BG}] "
set -g status-right "#[fg=${ACCENT}]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=${MUTED}]#h "
set -g window-status-format "#[fg=${MUTED}] #I:#W "
set -g window-status-current-format "#[fg=${ACCENT},bold] #I:#W "
set -g pane-border-style "fg=${BORDER}"
set -g pane-active-border-style "fg=${ACCENT}"
set -g message-style "bg=${BG},fg=${ACCENT}"
set -g message-command-style "bg=${BG},fg=${ACCENT}"
set -g mode-style "bg=${ACCENT},fg=${BG}"
setw -g clock-mode-colour ${ACCENT}
EOF

# ── Reload tmux if a session is running ───────────────────────
if command -v tmux >/dev/null 2>&1 && tmux list-sessions >/dev/null 2>&1; then
    tmux source-file "$HOME/.config/tmux/tmux.conf" 2>/dev/null || true
fi

echo "tmux theme applied: ${THEME} (${BASE})"
