#!/bin/bash

# ========================================
# Nmux42 Uninstaller Script
# Reverts changes made by setup.sh
# ========================================

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Confirmation
read -p "Are you sure you want to uninstall Nmux42 and revert configuration changes? (y/N): " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    print_info "Uninstall cancelled."
    exit 0
fi

# 1. Restore .zshrc
print_info "Restoring .zshrc..."
ZSHRC="$HOME/.zshrc"
if [ -f "${ZSHRC}.bak" ]; then
    mv "${ZSHRC}.bak" "$ZSHRC"
    print_success ".zshrc restored from backup."
else
    if [ -f "$ZSHRC" ]; then
        # Check if it was our generated file
        if grep -q "Organized ZSH Configuration" "$ZSHRC"; then
            rm "$ZSHRC"
            print_success "Removed generated .zshrc (no backup found)."
        else
            print_warning ".zshrc does not appear to be generated by Nmux42. Skipping."
        fi
    fi
fi

# 2. Remove Configurations
print_info "Removing configuration directories..."
rm -rf "$HOME/.config/tmux"
rm -f "$HOME/.tmux.conf"

if [ -d "$HOME/.config/nvim" ]; then
    rm -rf "$HOME/.config/nvim"
    print_success "Removed ~/.config/nvim."
    
    # Check for backups created by setup.sh
    LATEST_BAK=$(ls -td "$HOME"/.config/nvim.bak.* 2>/dev/null | head -n 1)
    if [ -n "$LATEST_BAK" ]; then
        read -p "Found a Neovim backup at $(basename "$LATEST_BAK"). Restore it? (y/N): " restore_nvim
        if [[ "$restore_nvim" =~ ^[Yy]$ ]]; then
            mv "$LATEST_BAK" "$HOME/.config/nvim"
            print_success "Restored Neovim configuration from $LATEST_BAK."
        fi
    fi
fi

# 3. Remove User-space Binaries
print_info "Removing user-space binaries..."
rm -f "$HOME/.local/bin/lazygit"
rm -f "$HOME/.local/bin/nvim"
rm -rf "$HOME/.local/share/nvim-dist"

# 4. Remove Node.js / NVM / NPM Global
if [ -d "$HOME/.nvm" ]; then
    read -p "Remove NVM and all installed Node.js versions in ~/.nvm? (y/N): " remove_nvm
    if [[ "$remove_nvm" =~ ^[Yy]$ ]]; then
        rm -rf "$HOME/.nvm"
        print_success "Removed ~/.nvm."
    fi
fi

if [ -d "$HOME/.npm-global" ]; then
    read -p "Remove NPM global packages in ~/.npm-global (japonette, etc)? (y/N): " remove_npm
    if [[ "$remove_npm" =~ ^[Yy]$ ]]; then
        rm -rf "$HOME/.npm-global"
        print_success "Removed ~/.npm-global."
    fi
fi

# 5. Remove Local Homebrew (Linuxbrew)
if [ -d "$HOME/.linuxbrew" ]; then
    read -p "Remove locally installed Homebrew in ~/.linuxbrew? (y/N): " remove_brew
    if [[ "$remove_brew" =~ ^[Yy]$ ]]; then
        rm -rf "$HOME/.linuxbrew"
        print_success "Removed ~/.linuxbrew."
    fi
fi

# 6. Remove Fonts
print_info "Cleaning up fonts..."
if [ -d "$HOME/.local/share/fonts" ]; then
    find "$HOME/.local/share/fonts" -name "JetBrainsMono*" -delete
    if command -v fc-cache >/dev/null 2>&1; then
        fc-cache -f "$HOME/.local/share/fonts" 2>/dev/null || true
    fi
    print_success "Removed JetBrainsMono Nerd Fonts."
fi

# 7. Final Instructions
print_info "--- Uninstall Complete ---"
print_warning "Note: System packages installed via pacman/apt/dnf/brew were NOT removed."
if [ "$SHELL" != "/bin/bash" ]; then
    print_info "Your current shell is $SHELL. To revert to bash, run: chsh -s /bin/bash"
fi
print_success "Nmux42 has been removed. Please restart your terminal."
