return {
    "nvim-lua/plenary.nvim",
    "nvim-tree/nvim-web-devicons",
    { "nvim-treesitter/nvim-treesitter",             branch = "main" },
    { "nvim-treesitter/nvim-treesitter-textobjects", branch = "main" },
    "nvim-treesitter/nvim-treesitter-context",
    "nvim-telescope/telescope.nvim",
    { "ThePrimeagen/harpoon", branch = "harpoon2" },
    "folke/tokyonight.nvim",
    "scottmckendry/cyberdream.nvim",
    "nvim-lualine/lualine.nvim",
    "brenoprata10/nvim-highlight-colors",
    "nvim-orgmode/orgmode",
    "tpope/vim-fugitive",
    "mbbill/undotree",
    "ojroques/vim-oscyank",
    "kkoomen/vim-doge",
    "captbaritone/better-indent-support-for-php-with-html",
    "williamboman/mason.nvim",
    "pbondoer/vim-42header",
    "MunifTanjim/nui.nvim",
    "nvim-neo-tree/neo-tree.nvim",
    "goolord/alpha-nvim",
    -- Git
    "lewis6991/gitsigns.nvim",
    "kdheepak/lazygit.nvim",

    -- Preinstalled themes
    { "catppuccin/nvim",        name = "catppuccin" },
    "Mofiqul/vscode.nvim",
    "ellisonleao/gruvbox.nvim",
    "shaunsingh/nord.nvim",
    "tahayvr/matteblack.nvim",
    { "rose-pine/neovim",       name = "rose-pine" },
    "rebelot/kanagawa.nvim",
    "EdenEast/nightfox.nvim",
    { "bjarneo/aether.nvim",    branch = "v3" },
}
